services:
  - type: web
    name: lab-ti-polinema
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 4000
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: db_lab_ilkom
      - key: DB_SSL
        value: true
      - key: JWT_SECRET
        generateValue: true
